# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get install wget
    wget http://apache.cs.utah.edu/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
    tar xvzf apache-maven-3.6.3-bin.tar.gz
  displayName: 'Configure Tools'
- script: |
    export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
    cd scripts
    make release
  displayName: 'Build Feature'

- script: |
     # Determine if this is a tagged release
     echo "upload release"
     current_branch=`git symbolic-ref --short HEAD`
     echo "Active branch: ${current_branch"
     if test "${current_branch}" = "master"; then
       git describe --exact-match `git rev-parse HEAD`
       if test $? -ne 0; then
         echo "Snapshot release"
         cd scripts
         make upload-testing -DBINTRAY_USERNAME=$(BINTRAY_USERNAME) -DBINTRAY_API_KEY=$(BINTRAY_API_KEY)
       else
         echo "Full release"
         cd scripts
         make upload-release -DBINTRAY_USERNAME=$(BINTRAY_USERNAME) -DBINTRAY_API_KEY=$(BINTRAY_API_KEY)
       fi
     else
       echo "Note: not releasing from non-master branch"
     fi
  displayName: 'Upload release'

