/*
 * generated by Xtext 2.12.0
 */
package org.psstools.psde.lang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;

import org.eclipse.xtext.util.Modules2;
import org.psstools.psde.lang.PSSRuntimeModule;
import org.psstools.psde.lang.PSSStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PSSIdeSetup extends PSSStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PSSRuntimeModule(), new PSSIdeModule()));
	}
	
}
