/*
 * generated by Xtext 2.12.0
 */
package net.sf.psstools.lang;

import org.eclipse.xtext.naming.IQualifiedNameConverter;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;

import com.google.inject.Binder;

import net.sf.psstools.lang.scoping.PSSQualifiedNameConverter;
import net.sf.psstools.lang.scoping.PSSQualifiedNameProvider;
import net.sf.psstools.lang.scoping.PSSResourceDescriptionStrategy;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PSSRuntimeModule extends AbstractPSSRuntimeModule {

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(IDefaultResourceDescriptionStrategy.class)
			.to(PSSResourceDescriptionStrategy.class);		
	}

//	def bindIResourceDescriptionStrategy() {
//		System.out.println("bindIResourceDescriptionStrategy");
//		return PSSResourceDescriptionStrategy;
//	}
//	
//	def bindDefaultResourceDescriptionStrategy() {
//		System.out.println("bindDefaultResourceDescriptionStrategy");
//		return PSSResourceDescriptionStrategy;
//	}
//	
//	def bindIResourceServiceProvider() {
//		return PSSResourceServiceProvider;
//	}

	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return PSSQualifiedNameProvider.class;
	}
	
	public Class<? extends IQualifiedNameConverter> bindIQualifiedNameConverter() {
		return PSSQualifiedNameConverter.class;
	}
}
