/*
 * generated by Xtext 2.10.0
 */
package net.sf.psstools.lang


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PSSRuntimeModule extends AbstractPSSRuntimeModule {
}
