/*
 * generated by Xtext 2.12.0
 */
package net.sf.psstools.lang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PSSStandaloneSetup extends PSSStandaloneSetupGenerated {

	public static void doSetup() {
		new PSSStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
