/*
 * generated by Xtext 2.10.0
 */
package net.sf.psstools.lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PSSStandaloneSetup extends PSSStandaloneSetupGenerated {

	def static void doSetup() {
		new PSSStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
