/*
 * generated by Xtext 2.12.0
 */
package net.sf.psstools.lang.ui.contentassist;

import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class PSSProposalProvider extends AbstractPSSProposalProvider {

	@Override
	public void completeKeyword(Keyword keyword, ContentAssistContext contentAssistContext,
			ICompletionProposalAcceptor acceptor) {
		// TODO Auto-generated method stub
	//	super.completeKeyword(keyword, contentAssistContext, acceptor);
	}
	
	
}
