/*
 * generated by Xtext 2.10.0
 */
package net.sf.psstools.lang.ui.tests;

import com.google.inject.Injector;
import net.sf.psstools.lang.ui.internal.LangActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class PSSUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LangActivator.getInstance().getInjector("net.sf.psstools.lang.PSS");
	}

}
