/*
 * generated by Xtext 2.12.0
 */
package org.psstools.psde.lang.ui.tests;

import com.google.inject.Injector;

import org.eclipse.xtext.testing.IInjectorProvider;
import org.psstools.psde.lang.ui.internal.LangActivator;

public class PSSUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LangActivator.getInstance().getInjector("org.psstools.psde.lang.PSS");
	}

}
