/*
 * generated by Xtext 2.12.0
 */
package org.psstools.psde.lang;

import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;
import org.psstools.psde.lang.scoping.PSSResourceDescriptionStrategy;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PSSRuntimeModule extends AbstractPSSRuntimeModule {

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(IDefaultResourceDescriptionStrategy.class)
			.to(PSSResourceDescriptionStrategy.class);		
	}

//	def bindIResourceDescriptionStrategy() {
//		System.out.println("bindIResourceDescriptionStrategy");
//		return PSSResourceDescriptionStrategy;
//	}
//	
//	def bindDefaultResourceDescriptionStrategy() {
//		System.out.println("bindDefaultResourceDescriptionStrategy");
//		return PSSResourceDescriptionStrategy;
//	}
//	
//	def bindIResourceServiceProvider() {
//		return PSSResourceServiceProvider;
//	}
	
}
