/*
 * generated by Xtext 2.12.0
 */
package net.sf.psstools.lang.ide

import com.google.inject.Guice
import net.sf.psstools.lang.PSSRuntimeModule
import net.sf.psstools.lang.PSSStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class PSSIdeSetup extends PSSStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new PSSRuntimeModule, new PSSIdeModule))
	}
	
}
