/*
 * generated by Xtext 2.12.0
 */
package net.sf.psstools.lang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import net.sf.psstools.lang.PSSRuntimeModule;
import net.sf.psstools.lang.PSSStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PSSIdeSetup extends PSSStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PSSRuntimeModule(), new PSSIdeModule()));
	}
	
}
